<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="ko"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ValidExceptionHandler.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">spring-todo-management</a> &gt; <a href="index.source.html" class="el_package">com.scw.springtodomanagement.common.exceptionhadler</a> &gt; <span class="el_source">ValidExceptionHandler.java</span></div><h1>ValidExceptionHandler.java</h1><pre class="source lang-java linenums">package com.scw.springtodomanagement.common.exceptionhadler;

import com.scw.springtodomanagement.common.global.response.ErrorResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.NestedExceptionUtils;
import org.springframework.core.annotation.Order;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.util.concurrent.ConcurrentHashMap;

import static com.scw.springtodomanagement.common.errorcode.CommonErrorCode.BAD_REQUEST;

<span class="fc" id="L17">@Slf4j</span>
@Order(1)
@RestControllerAdvice
<span class="fc" id="L20">public class ValidExceptionHandler {</span>

    /**
     * 유효성 검사에서 예외가 발생
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    protected ResponseEntity&lt;ErrorResponse&gt; validException(MethodArgumentNotValidException e) {
<span class="fc" id="L27">        log.error(&quot;[MethodArgumentNotValidException] cause : {}, message : {} &quot;, NestedExceptionUtils.getMostSpecificCause(e),e.getMessage());</span>

<span class="fc" id="L29">        ConcurrentHashMap&lt;Object, Object&gt; validationMessage = new ConcurrentHashMap&lt;&gt;();</span>
<span class="fc bfc" id="L30" title="All 2 branches covered.">        for (FieldError fieldError : e.getFieldErrors()) {</span>
<span class="fc" id="L31">            validationMessage.put(fieldError.getField(), fieldError.getDefaultMessage());</span>
<span class="fc" id="L32">        }</span>

<span class="fc" id="L34">        ErrorResponse errorResponse = ErrorResponse.of(BAD_REQUEST, validationMessage);</span>

<span class="fc" id="L36">        return ResponseEntity.status(BAD_REQUEST.getHttpStatusCode())</span>
<span class="fc" id="L37">                .body(errorResponse);</span>
    }


}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.11.202310140853</span></div></body></html>